### ISSUE TITLE
Remove unused `demo` commands

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-zkevm-ibc-demo#49]
## Context

There is scaffolding that was created in the demo CLI in the testing/demo/pkg directory. The scaffolding wasn't used and the implementation for `make setup` exists in testing/demo/pkg/setup.

## Problem

`make setup` doesn't use the scaffolding in the demo CLI. As a result, all of this is unused:
1. https://github.com/celestiaorg/celestia-zkevm-ibc-demo/blob/d1edc7887c7efa4a3424355e02b8206462eada80/testing/demo/main.go#L39-L61
2. https://github.com/celestiaorg/celestia-zkevm-ibc-demo/blob/d1edc7887c7efa4a3424355e02b8206462eada80/testing/demo/pkg/deploy_contracts.go#L8-L25
3. https://github.com/celestiaorg/celestia-zkevm-ibc-demo/blob/d1edc7887c7efa4a3424355e02b8206462eada80/testing/demo/pkg/establish_transfer_channels.go#L1-L6

## Proposal

Option A: remove all these unused files
Option B: retrofit `make setup` to use the `demo` CLI. Move the implementation inside `demo/pkg/setup` into the appropriate files: deploy_contracts.go, establish_transfer_channels.go

**Comment by cmwaters** [comment]
I think we can just remove all this for now. This was my first attempt at scaffolding together the demo
