### ISSUE TITLE
Establish an IBC client on both the reth rollup and simapp chain

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-zkevm-ibc-demo#7]
Before being able to pass transfer messages, we need to set up light clients on both the reth rollup and on the simapp chain (and afterwards setup the channels).

For simapp, the following message needs to be submitted (but repurposed for the groth16 IBC Client):

https://github.com/cosmos/solidity-ibc-eureka/blob/55e908e87c330afec4cb516a59419b993366b092/e2e/interchaintestv8/e2esuite/light_clients.go#L304

For reth, the following message on the tendermintX smart contract needs to be sent. More information can be found in [sp1-ics07-tendermint](https://github.com/cosmos/sp1-ics07-tendermint)

We should be able to verify through queries that both of these clients have been initialised and what their unique ID is

**Comment by rootulp** [comment]
@ninabarbakadze mentioned this was done and I'm guessing https://github.com/celestiaorg/celestia-zkevm-ibc-demo/commit/60e39eacb54b7f531650cbe275f98fab3013e118 resolved it. If that's the case, can we close this issue?
